### ISSUE TITLE
sent prerouted pbuf

### ISSUE THREAD

**Issue by idimi-dodjimi** [russdill/lwip-nat#3]
Hi Russ,

Looking at your example I am missing the point where pre-routed packet is sent.
after ip4_prerouting_nat nothing has been done with the pbuf. It was just freed and newer send anywhere. Have I missed something?

Thanks,
Srdjan

**Comment by russdill** [comment]
It just modifies the packet before lwIP makes a routing decision. It only
calls pbuf_free if the packet shouldn't continue though lwIP
(ip4_prerouting_hook returns 1).

**Comment by idimi-dodjimi** [comment]
I see, 

thanks for the info.

Srdjan
