### ISSUE TITLE
sys_timeout calling nat_timer_tick

### ISSUE THREAD

**Issue by jolie1204** [russdill/lwip-nat#6]
In function nat_init(), sys_timeout() was called with the second argument nat_timer_tick.
Don't you have to pass "nat_timer" as the second parameter for sys_timeout?

I changed it to nat_timer in my use case, and it's working, but without having the change I mentioned, it runs out of pcb and NAT stops working after maximum pcb is used.

By the way, thanks for this wonderful project.

**Comment by russdill** [comment]
Thanks for the fix, it's a pretty clear typo.
